[window]
opacity = 0.9
startup_mode = "Maximized"

[font]
size = 10.25
normal = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Regular" }
bold = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Bold" }
italic = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Italic" }
bold_italic = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Bold Italic" }

[mouse]
hide_when_typing = true

[env]
term = "xterm-256color"

# Default colors
[colors.primary]
background = '#161616'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'
