[window]
opacity = 0.95
startup_mode = "Maximized"

[font]
size = 10.25
normal = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Regular" }
bold = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Bold" }
italic = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Italic" }
bold_italic = { "family" = "JetbrainsMonoNL Nerd Font Propo", style = "Bold Italic" }

[mouse]
hide_when_typing = true
