[manager]
show_hidden = true

[opener]
play = [
	{ run = 'vlc "$@"', block = true, orphan = true, for = "unix" },
]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', block = true, desc = "Open" },
]
